"   General
syntax on
set number			" Show line numbers
set relativenumber
set showmatch			" Highlight matching brace
set nowrap
set noswapfile
set hlsearch			" Highlight all search results
set smartcase			" Enable smart-case search
set ignorecase			" Always case-insensitive
set incsearch			" Searches for strings incrementally
set autoindent			" Auto-indent new lines
set shiftwidth=4		" Number of auto-indent spaces
set smartindent			" Enable smart-indent
set smarttab			" Enable smart-tabs
set softtabstop=4		" Number of spaces per Tab
set nocompatible

"   Advanced
set ruler			" Show row and column ruler information
set undolevels=1000		" Number of undo levels
set backspace=indent,eol,start " Backspace behaviour 

"   Vim-Plug
call plug#begin()
Plug 'ternjs/tern_for_vim'
Plug 'ycm-core/YouCompleteMe'
Plug 'vim-airline/vim-airline'
Plug 'scrooloose/nerdtree'
Plug 'mg979/vim-visual-multi', {'branch': 'master'}
Plug 'arcticicestudio/nord-vim'
Plug 'vimsence/vimsence'
Plug 'pangloss/vim-javascript'
Plug 'jiangmiao/auto-pairs'
call plug#end()

colorscheme nord

"   Mappings
nmap <F6> :NERDTreeToggle<CR>
